Secondary button & grid for premium pages
cozy/cozy-bootstrap pull request #41
Opened 2021-08-16 15:42 UTC by aeris

2021-08-16 15:59 UTC, nono requested changes
This PR cannot be accepted currently:

- the tests are broken
- there are 2 changes (1. secondary button & 2. grid), so we should have 2 commits
- the commit message must follow the semantic-release rules

2021-08-16 15:59 UTC, nono commented on docs/buttons.html
> +          <button type="button" class="btn btn-secondary">Button</button>
Please keep the `btn-outline-info` here. It makes more sense with bootstrap (the secondary title is a reference to Material-UI and Joël's documentation).

2021-08-16 15:59 UTC, nono commented on postcss-cozy-vars/index.js
> +    // case ".btn-secondary:hover":
If you want to remove code, remove it, don't comment it

2021-08-16 15:59 UTC, nono commented on src/cozy/_colors.scss
> +  --secondaryColorDark: transparent;               // Secondary 700
I really don't think that the comment is still acurate after this change

2021-08-17 08:49 UTC, nono requested changes
I don't understand what you want to do. Why make the `btn-secondary`, `btn-outline-secondary`, and `btn-outline-info` look the same?

And, it is not OK to change the color of `text-secondary`. It is a color chosen by our designer.

2021-08-17 09:34 UTC, nono reviewed
Can you explain why it would be helpful to have the grid module? Can't we just use a few CSS grid rules? I think bootstrap grid module is quite big, and I would prefer to avoid the bloat if we just need a very small part of it.

And the commit message must follow the semantic-release rules (bis).

2021-08-17 10:07 UTC, aeris commented
After investigation, we will use directly bootstrap-grid from npm package for premium.
So this PR useless now.

2021-08-17 10:07 UTC, closed without merging